name: 平台构建部署

on:
  push:
    branches:
      - 'platform/*'
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    name: 构建和部署
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: true

      - name: 设置路径变量
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "MODE=tag" >> $GITHUB_ENV
            TAG_NAME=$(echo "${{ github.ref_name }}" | sed 's/^v//')
            echo "PATH_PREFIX=$REPO/platform/$TAG_NAME" >> $GITHUB_ENV
          else
            echo "MODE=$(echo "${{ github.ref_name }}" | sed 's/^platform\///')" >> $GITHUB_ENV
            echo "PATH_PREFIX=$REPO/${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: 安装依赖并构建
        run: |
          pnpm install --frozen-lockfile
          pnpm run lint:pkg
          pnpm run build:pkg
          cd project/platform && pnpm run build --base https://static.zxnum.com/$PATH_PREFIX/ --mode $MODE

      - name: 部署到 对象存储
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.S3_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          cos_bucket: ${{ secrets.S3_BUCKET }}
          cos_region: ${{ vars.S3_REGION }}
          local_path: project/platform/dist
          remote_path: $PATH_PREFIX/
          clean: false 