name: 平台构建部署

on:
  push:
    branches:
      - 'platform/*'

jobs:
  build-and-deploy:
    name: 构建和部署
    runs-on: ubuntu-latest
    container:
      image: ickeep/yimoka-frontend-ci:1.0.0
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装依赖并构建
        run: |
          pnpm install --frozen-lockfile
          pnpm run lint:pkg
          cd project/platform && pnpm run build

      - name: 配置 AWS 凭证
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.S3_REGION }}

      - name: 部署到 S3
        run: |
          aws --endpoint-url ${{ vars.S3_ENDPOINT }} s3 sync project/platform/dist s3://${{ secrets.S3_BUCKET }}/${{ github.repository }}/${{ github.ref_name }}/ 