name: 构建并发布 pnpm Docker 镜像

on:
  push:
    branches:
      - pnpm

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v3

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建并推送镜像
        uses: docker/build-push-action@v5
        with:
          context: ./devops/pnpm
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pnpm:10.8.1
            ${{ secrets.DOCKERHUB_USERNAME }}/pnpm:latest 